name: Version
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35.2.0
        
      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.18.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: "chore(release): {version}"
          preset: "angular"
          tag-prefix: "v"
          output-file: "CHANGELOG.md"
          skip-version-file: "true"
          skip-on-empty: "true"
          skip-commit: "true"

      - name: Upload to waspscripts.com
        uses: Torwent/wasp-upload-action@master
        with:
          SB_URL: ${{ secrets.SB_URL }}
          SB_ANON_KEY: ${{ secrets.SB_ANON_KEY }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          
      - name: Commit and push changes
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          git config --global user.name 'WaspBot'
          git config --global user.email 'wasp@waspscripts.com'
          git commit -am "chore: github action"
          git push
          
      - name: Create release
        uses: actions/create-release@v1.1.4
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
    
      - name: Discord notification
        uses: rguillaume/discord-action-embed@v1.0.4
        with:
          webhook: ${{ secrets.UPDATES_WEBHOOK }}
          embed: '{"title": "Update: ${{ github.event.repository.name }}", "description": ${{ toJSON(github.event.head_commit.message) }}, "url": "${{ github.event.head_commit.url }}", "footer": {"text": "Committer: ${{ github.event.head_commit.author.username }}"}, "color": "16760576"}'